apiVersion: v1
kind: Pod
metadata:
  name: "mypod1"
  labels:
    region: IN
   

spec:
  containers:
  - name: "myc2"
    image: "httpd"
    env:
    - name: x
      value: "5"


apiVersion: v1
kind: pod
metadata: 
    name: 