apiVersion: v1
kind: Pod
metadata:
    name: "mypod1"
spec:
    Containers:
    - name: "myc1"
      image: "httpd"
      volumeMounts:
      - mountPath: /etc/httpd/conf.d/
        name: mycm
    
    volumes:
    - configMap: 
        name: mywebcm
      name: mycm
